### ISSUE TITLE
The library needs to be installed to be able to run the tests

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/Ciw#2]
When running without installing from the base get:

```
======================================================================
ERROR: test_simulate_until_deadlock_method (asq.tests.test_simulation.TestSimulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "asq/tests/test_simulation.py", line 85, in test_simulate_until_deadlock_method
    Q = asq.Simulation(asq.load_parameters('tests/datafortesting/logs_test_for_deadlock_sim/'))
  File "asq/import_params.py", line 16, in load_parameters
    parameter_file = open(parameter_file_name, 'r')
IOError: [Errno 2] No such file or directory: '/Users/vince/src/Ciw/tests/datafortesting/logs_test_for_deadlock_sim/parameters.yml'

======================================================================
ERROR: test_simulate_until_max_time_method (asq.tests.test_simulation.TestSimulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "asq/tests/test_simulation.py", line 70, in test_simulate_until_max_time_method
    Q = asq.Simulation(asq.load_parameters('tests/datafortesting/logs_test_for_simulation/'))
  File "asq/import_params.py", line 16, in load_parameters
    parameter_file = open(parameter_file_name, 'r')
IOError: [Errno 2] No such file or directory: '/Users/vince/src/Ciw/tests/datafortesting/logs_test_for_simulation/parameters.yml'

----------------------------------------------------------------------
Ran 26 tests in 0.003s

FAILED (errors=18)
```

In other words the tests fail because of being able to find the `yml` files.

**Comment by geraintpalmer** [comment]
are you in correct directory? Don't run tests in Ciw/, run in Ciw/ciw/

**Comment by drvinceknight** [comment]
> are you in correct directory? Don't run tests in Ciw/, run in Ciw/ciw/

Yes that's the point. If you're in `Ciw/ciw` there is no longer a `ciw` to import unless you install. This is what needs to be fixed (you shouldn't need to install to run the tests).

**Comment by geraintpalmer** [comment]
So fixing the relative paths will fix this?

**Comment by drvinceknight** [comment]
> So fixing the relative paths will fix this?

I think so or simply changing the relative paths so that they expect the tests to run from the root of the project. :)
